version: '3.7'

volumes:
  data:
  nodemodules: {}

services:
  redis:
    volumes:
      - data:/data
    image: redis:latest
    expose:
      - 6379
  drones:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app/
      - nodemodules:/usr/app/node_modules
    depends_on:
      - redis
    command: npm run start